apiVersion: v1
kind: Service
metadata:
  name: appService-AppA-LoadBalancer
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: appService-AppA-NodePort
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: appService-AppA-ClusterIP
  labels:
    app: nginx
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: appService-AppA-ExternalName
  labels:
    app: nginx
spec:
  type: ExternalName
  ports:
  - port: 80
  selector:
    app: nginx